import { prisma } from "../lib/prisma.js";
import { getSocket } from "../socket.js";
import {
  NotificationType,
  IncidentEventType,
} from "../generated/prisma/client.js";
import { UserRole } from "../constants/user.js";

type CreateIncidentNotificationParams = {
  event: {
    id: string;
    type: IncidentEventType;
    incidentId: string;
    createdAt: Date;
  };
  orgId: string;
  actorUserId: string;
  title: string;
  message: string;
  metadata?: unknown;
};

type NotificationPayload = {
  id: string;
  incidentId: string;
  type: NotificationType;
  title: string;
  message: string;
  createdAt: Date;
};

function getNotificationType(
  eventType: IncidentEventType,
): NotificationType | null {
  switch (eventType) {
    case IncidentEventType.CREATED:
      return NotificationType.INCIDENT_CREATED;

    case IncidentEventType.ASSIGNED:
      return NotificationType.INCIDENT_ASSIGNED;

    case IncidentEventType.UPDATED:
    case IncidentEventType.STATUS_CHANGED:
    case IncidentEventType.SEVERITY_CHANGED:
      return NotificationType.INCIDENT_UPDATED;

    default:
      return null;
  }
}

function getNotificationRecipients(
  eventType: IncidentEventType,
  users: Array<{
    id: string;
    role: string;
  }>,
  assignedTo: string | null,
  metadata?: unknown,
): string[] {
  const recipientIds = new Set<string>();

  const data =
    metadata &&
    typeof metadata === "object" &&
    !Array.isArray(metadata)
      ? (metadata as Record<string, unknown>)
      : {};

  switch (eventType) {
    case IncidentEventType.CREATED: {
      /*
       * Incident creation:
       * - ADMIN receives notification
       * - MANAGER receives notification
       * - assigned MEMBER also receives notification
       */
      for (const user of users) {
        if (
          user.role === UserRole.ADMIN ||
          user.role === UserRole.MANAGER
        ) {
          recipientIds.add(user.id);
        }
      }

      if (assignedTo) {
        recipientIds.add(assignedTo);
      }

      break;
    }

    case IncidentEventType.ASSIGNED: {
      /*
       * Assignment:
       * Only the new assignee receives the notification.
       */
      const newAssignee =
        typeof data.to === "string" ? data.to : null;

      if (newAssignee) {
        recipientIds.add(newAssignee);
      }

      break;
    }

    case IncidentEventType.UPDATED:
    case IncidentEventType.STATUS_CHANGED:
    case IncidentEventType.SEVERITY_CHANGED: {
      /*
       * Incident update:
       * - ADMIN receives notification
       * - MANAGER receives notification
       * - assigned MEMBER receives notification
       *
       * Set prevents duplicates if the assigned user is also
       * an ADMIN or MANAGER.
       */
      for (const user of users) {
        if (
          user.role === UserRole.ADMIN ||
          user.role === UserRole.MANAGER
        ) {
          recipientIds.add(user.id);
        }
      }

      if (assignedTo) {
        recipientIds.add(assignedTo);
      }

      break;
    }

    default:
      break;
  }

  return [...recipientIds];
}

export async function createIncidentNotification({
  event,
  orgId,
  actorUserId,
  title,
  message,
  metadata,
}: CreateIncidentNotificationParams): Promise<void> {
  const notificationType = getNotificationType(event.type);

  if (!notificationType) {
    return;
  }

  /*
   * Get the incident and organization users.
   */
  const [incident, users] = await Promise.all([
    prisma.incident.findFirst({
      where: {
        id: event.incidentId,
        orgId,
      },
      select: {
        id: true,
        assignedTo: true,
      },
    }),

    prisma.user.findMany({
      where: {
        orgId,
      },
      select: {
        id: true,
        role: true,
      },
    }),
  ]);

  if (!incident) {
    return;
  }

  const recipientIds = getNotificationRecipients(
    event.type,
    users,
    incident.assignedTo,
    metadata,
  );

  if (recipientIds.length === 0) {
    return;
  }

  /*
   * The title and message are generated by the
   * incident event service.
   *
   * This service only persists and delivers them.
   */
  const notifications = await prisma.notification.createManyAndReturn({
    data: recipientIds.map((userId) => ({
      orgId,
      userId,
      incidentId: incident.id,
      incidentEventId: event.id,
      type: notificationType,
      title,
      message,
    })),

    skipDuplicates: true,

    select: {
      id: true,
      userId: true,
      incidentId: true,
      type: true,
      title: true,
      message: true,
      createdAt: true,
    },
  });

  /*
   * The actor's notification is persisted in the database,
   * but the actor does NOT receive the realtime Socket.IO event.
   */
  const socketNotifications = notifications.filter(
    (notification) => notification.userId !== actorUserId,
  );

  if (socketNotifications.length === 0) {
    return;
  }

  emitIncidentNotifications(socketNotifications);
}

function emitIncidentNotifications(
  notifications: Array<{
    id: string;
    userId: string;
    incidentId: string;
    type: NotificationType;
    title: string;
    message: string;
    createdAt: Date;
  }>,
): void {
  try {
    const io = getSocket();

    for (const notification of notifications) {
      const payload: NotificationPayload = {
        id: notification.id,
        incidentId: notification.incidentId,
        type: notification.type,
        title: notification.title,
        message: notification.message,
        createdAt: notification.createdAt,
      };

      io.to(`user:${notification.userId}`).emit(
        "notification",
        payload,
      );
    }
  } catch (error) {
    /*
     * The notification is already persisted in the database.
     * Socket.IO failure must not fail the incident operation.
     */
    console.error(
      "Failed to emit incident notification:",
      error,
    );
  }
}
